config/routes.rb
Rails.application.routes.draw do
 
 
  devise_for :users

	resources :users, only: [:show, :edit, :update, :index]
	resources :books
	root 'home#top'
	get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :user_id, presence: :true
	validates :title, presence: true
	validates :body ,presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,  :trackable, :validatable

  attachment :profile_image, destroy: false
  has_many :books
  validates :introduction, length: {maximum: 50}
  validates :name, presence: true, length: {in: 2..50}
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
before_action :configure_permitted_parameters, if: :devise_controller?

	private

	def after_sign_in_path_for(resource)
		user_path(resource)
	end

	def  after_sign_out_path_for(resource)
		root_path
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end

	def current_user?(user)
		if current_user.nil?
			return false
		else
			user.id.equial?(current_user.id)
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		@user = current_user
		@book = Book.new
		@books = Book.all
	end

	def new
		@books = Book.all
		@book = Book.new
	end

	def show
		@user = current_user
		@boo = Book.find(params[:id])
		@book = Book.new
	end

	def edit
		@book = Book.find(params[:id])
	end

	def create
		book = Book.new(book_params)
		book.user_id = current_user.id
		book.save
		redirect_to book_path(book.id)
	end

	def update
		book = Book.find(params[:id])
		book.update(book_params)
		redirect_to book_path(book.id)
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to new_path
	end
	private
	def book_params
		params.require(:book).permit(:title, :body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :screen_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def edit
  	@user = User.find(params[:id])
  end

   def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
       redirect_to user_path(@user), alert: "編集に成功しました"
    else
      render 'edit'
    end
  end

  private
    def user_params
    	params.require(:user).permit(:name, :introduction, :profile_image)
    end

  def screen_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb

<h2>New Book</h2>
<%= form_for book do |f| %>

<%= f.text_field :title %><br>
<%= f.text_area :body %><br>

<%= f.submit %>

<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for @book do |f| %>
<h4>title</h4>
	<%= f.text_field :title %>
<h4>Body</h4>
	<%= f.text_area :body %>
	<%= f.submit %>
<% end %>

<%=  link_to 'show', books_path(@book.id) %> <%=  link_to 'Back',  books_path%>

app/views/books/index.html.erb
<div class = info >
	<%= render 'users/info', user: @user %>
</div>
<%= render 'books/new', book: @book %>

<table>
	<tr><th>title</th><th>Body</th></tr>
<% @books.each do |book| %>
<tr>
	<td><%= book.title %></td>
	<td><%= book.body %></td>
	
</tr>
<% end %>
</table>

app/views/books/new.html.erb
<h1>Books</h1>

<table>
	<tr><th>title</th><th>Body</th></tr>
<% @books.each do |book| %>
<tr>
	<td><%= book.title %></td>
	<td><%= book.body %></td>
	<td><%=  link_to 'show',  book_path(book.id) %></td>
	<td><%=  link_to 'edit',  edit_book_path(book.id) %></td>
	<td><%=  link_to 'Destroy',  book_path(book.id), method: :delete %></td>
</tr>
<% end %>
</table>

<h2>New book</h2>
<%= form_for @book do |f| %>
<h4>title</h4>
	<%= f.text_field :title %>
<h4>Body</h4>
	<%= f.text_area :body %>
	<%= f.submit %>
<% end %>

app/views/books/show.html.erb
<div class = info >
	<%= render 'users/info', user: @user %>
</div>
	<%= render 'new', book: @book %>



<h1> Book Deteil</h1>
<table>
<tr>
<td><%= attachment_image_tag @user, :profile_image, :fill, 15, 15 %></td>
<td><%= @boo.title %></td>
<td><%= @boo.body %></td>
<td><%=  link_to 'edit',  edit_book_path(@boo.id) %></td>
<td><%=  link_to 'Destroy',  book_path(@boo.id), method: :delete %></td>
</tr>
</table>

app/views/home/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/home/top.html.erb
<div class ="top btn-group-vertical btn-group-sm center-block" >
		<%= link_to 'Log in', new_user_session_path, class: "btn btn-default btn-primary" %>
		<%= link_to 'sign up',new_user_registration_path, class: "btn btn-default btn-primary" %>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h2>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_header.html.erb

<% if user_signed_in? %>
	<header >
		<nav>
			<li class = "nav-logo" >
				Bookers
			</li>
			<ul class = "nav-list">
				<li class = "nav-list-item"><%= link_to 'home', user_path(current_user.id), class:"glyphicon glyphicon-home home" %></li>
				<li class = "nav-list-item"><%= link_to 'users', users_path, class: "glyphicon glyphicon-user users"%></li>
				<li class = "nav-list-item"><%= link_to 'Books', books_path , class: "glyphicon glyphicon-book books"%></li>
				<li class = "nav-list-item"><%= link_to 'log out', destroy_user_session_path, method: :delete ,  class: "glyphicon glyphicon-log-out logaut"%></li>
			</ul>
		</nav>
	</header>
<% else %>
	<header>
		<nav >
			<li class = "nav-logo" >
				Bookers
			</li>
			<ul class = "nav-list">
				<li class = "nav-list-item"><%= link_to 'home', root_path , class:"glyphicon glyphicon-home home" %></li>
				<li class = "nav-list-item"><%= link_to 'about', home_about_path, class:"glyphicon glyphicon-link about"  %></li>
				<li class = "nav-list-item"><%= link_to 'sign_up',  new_user_registration_path , class:"glyphicon glyphicon-edit signup" %></li>
				<li class = "nav-list-item"><%= link_to 'login', new_user_session_path, class:"glyphicon glyphicon-log-in login"  %></li>
			</ul>
		</nav>
	</header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    
  <%= render partial: "layouts/header" %>

    <%= yield %>
  </body>
</html>

app/views/users/_info.html.erb

<h2>User Info</h4>
<% if @profile_image_id == nil %>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<% elsif %>
<%= attachment_image_tag user, :profile_image %>
<% end %>
<br>
name : <%= user.name %>
<br>
introduction :<%= user.introduction %>
<br>
<%= link_to '編集',  edit_user_path(user.id) %>


app/views/users/edit.html.erb
<h2>User Info</h4>

<%= form_for(@user) do |user| %>
<%= render 'layouts/errors', obj: @user %>
name : <%= user.text_field :name %>
<%= user.attachment_field :profile_image %>
introduction :<%= user.text_area :introduction %>

<%= user.submit %>
<% end %>

app/views/users/index.html.erb
<div class = info >
	<%= render 'users/info', user: @user %>
</div>
<%= render 'books/new', book: @book %>

<table>
	<tr><th>image</th><th>name</th></tr>
<% @users.each do |user| %>
<tr>
	<td><%= attachment_image_tag user, :profile_image, :fill, 15, 15 %>
</td>
	<td><%= user.name %></td>

<td><%= link_to 'show', user_path(user.id) %></td>
</tr>
<% end %>
</table>

app/views/users/show.html.erb
<%= alert %>
<div class = info >
	<%= render 'users/info', user: @user %>
</div>
<%= render 'books/new', book: @book %>

<h2>Books</h2>
<table>
	<tr><th></th><th>title</th><th>opinion</th></tr>
<% @books.each do |book| %>
<tr>
	<td></td>
<td><%= link_to book.title ,book_path(book.id) %></td>
<td><%= book.body %></td>
</tr>
<% end %>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>